# -*- coding: utf-8 -*-
"""Video_2_frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fc_8hA3Hv9vt3OK1SdXk2AIF8e5O41dr
"""

import cv2
import os 
#from google.colab import drive

#drive.mount('/content/drive')
directory_path='Extracted'
video_path = 'video2.mp4'
PERIOD=10

video = cv2.VideoCapture(video_path)
success = True
count = 1

    
if not os.path.exists(directory_path):
    os.makedirs(directory_path)
print(f"Directory '{directory_path}' created.")


while success:

    success,frame = video.read()
  
    if success == True:
    
        if count%PERIOD==0:
            name = directory_path+'/'+str(count)+'.jpg'
            cv2.imwrite(name,frame)
            print('Frame {} Extracted Successfully'.format(count))

    else:
       
        break
        
    count = count+1  
    
  
  
  
  